spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    # 数据库初始化脚本使用utf-8字符集(解决@JdbcTest乱码问题)
    sql-script-encoding: utf-8

server:
  context-path: /
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true